### ISSUE TITLE
How to use custom images

### ISSUE THREAD

**Issue by chulaihunde** [lukas-blecher/LaTeX-OCR#101]
I used the command to generate my png images：
convert -density 250 -colorspace gray -flatten /tmp/eqcjtqs0o1.pdf -quality 90 /tmp/eqcjtqs0o1.png

identify  /tmp/eqcjtqs0o1.png
/tmp/eqcjtqs0o1.png PNG 308x86 308x86+0+0 8-bit Gray 16c 1783B 0.000u 0:00.000

And  we generate the datasets,  When training, make mistakes :

Traceback (most recent call last):
  File "/home/long/Latex_ORC/LaTeX-OCR-main/train.py", line 89, in <module>
    train(args)
  File "/home/long//Latex_ORC/LaTeX-OCR-main/train.py", line 48, in train
    encoded = encoder(im.to(device))
  File "/home/long/anaconda3/envs/LaTexORC_py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/long/anaconda3/envs/LaTexORC_py39/lib/python3.9/site-packages/timm/models/vision_transformer.py", line 363, in forward
    x = self.forward_features(x)
  File "/home/long/Latex_ORC/LaTeX-OCR-main/models.py", line 80, in forward_features
    x += self.pos_embed[:, pos_emb_ind]
RuntimeError: The size of tensor a (121) must match the size of tensor b (88) at non-singleton dimension 1

**Comment by lukas-blecher** [comment]
The images need to be preprocessed in a way that the dimensions of every image can be divisible by the patch size
I've used the following method:
https://github.com/lukas-blecher/LaTeX-OCR/blob/b5217d2b9938b7d7c7f4f27c581985c9c112f254/utils/utils.py#L73-L104
