### ISSUE TITLE
GUI and pix2tex fails to launch (probably, not x_transformers issue)

### ISSUE THREAD

**Issue by SN-CH** [lukas-blecher/LaTeX-OCR#104]
When attempting to launch gui.py, I get the following error:
```
sn@sn-5-hrl:/opt/LaTeX-OCR-main$ python3 ./gui.py 
Traceback (most recent call last):
  File "./gui.py", line 274, in <module>
    ex = App(arguments)
  File "./gui.py", line 26, in __init__
    self.initModel()
  File "./gui.py", line 33, in initModel
    args, *objs = pix2tex.initialize(self.args)
  File "/opt/LaTeX-OCR-main/pix2tex.py", line 55, in initialize
    model.load_state_dict(torch.load(args.checkpoint, map_location=args.device))
  File "/home/sn/.local/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/sn/.local/lib/python3.8/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
```
Having read comments to similar issues here I can confirm the `x_transformers` package has version number 0.15.0 in my Lubuntu, I have double checked it (that being said, I tried the latest 25th version of the package as well, no dice). All packages listed in `requirements.txt` are installed. So are the third-party programs mentioned in `readme`. I use Python 3.8, though.

On the other hand, pix2tex.py fails too (the same problem as far as I can judge):
```
sn@sn-5-hrl:/opt/LaTeX-OCR-main$ python3 ./pix2tex.py 
Traceback (most recent call last):
  File "pix2tex.py", line 146, in <module>
    args, *objs = initialize(arguments)
  File "pix2tex.py", line 55, in initialize
    model.load_state_dict(torch.load(args.checkpoint, map_location=args.device))
  File "/home/sn/.local/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/sn/.local/lib/python3.8/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
```
Any guesses would be much appreciated.

**Comment by lukas-blecher** [comment]
Looks like the checkpoint file is empty or the download was interrupted.
Check the file size of `weights.pth` and redownload it if its below 97MB

**Comment by SN-CH** [comment]
Thank you for the suggestion. I re-installed those packages, but that did not help.

Yes, I use Lubuntu (more or less standard installation, not something heavily customised). I wonder if some one else reported such behaviour.
