### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by calmisential** [lukas-blecher/LaTeX-OCR#126]
When I run `latexocr` in Windows Terminal, I got this error:
```
Traceback (most recent call last):
  File "F:\Python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "F:\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\Venv\pytorch_1.11\Scripts\latexocr.exe\__main__.py", line 7, in <module>
  File "F:\Venv\pytorch_1.11\lib\site-packages\pix2tex\gui.py", line 316, in main
    with in_model_path():
  File "F:\Python\lib\contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "F:\Venv\pytorch_1.11\lib\site-packages\pix2tex\utils\utils.py", line 161, in in_model_path
    with path('pix2tex', 'model') as model_path:
  File "F:\Python\lib\contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "F:\Python\lib\importlib\resources.py", line 175, in _path_from_reader
    opener_reader = reader.open_resource(norm_resource)
  File "<frozen importlib._bootstrap_external>", line 1055, in open_resource
PermissionError: [Errno 13] Permission denied: 'F:\\Venv\\pytorch_1.11\\lib\\site-packages\\pix2tex\\model'
```

**Comment by lukas-blecher** [comment]
That's weird. Can you tell me about your setup? Is `F:\` an extern drive?
I tried to replicate it but I only found that the gui requirements weren't met (`pip install pix2tex[gui]` to solve that problem).

But I don't know what's happening here. Can you try with an admin cmd?

**Comment by calmisential** [comment]
Thanks for your response. `F:\` is not an extern drive, and I install `pix2tex` in python virtual env. Could this be the reason?

**Comment by calmisential** [comment]
These are what I've installed in the virtual python env:
```
Package                 Version
----------------------- ---------
absl-py                 1.0.0
albumentations          1.1.0
anyio                   3.4.0
argon2-cffi             21.3.0
argon2-cffi-bindings    21.2.0
attrs                   21.4.0
Babel                   2.9.1
backcall                0.2.0
bleach                  4.1.0
cachetools              4.2.4
certifi                 2021.10.8
cffi                    1.15.0
chardet                 4.0.0
charset-normalizer      2.0.10
click                   8.1.2
colorama                0.4.4
cycler                  0.11.0
debugpy                 1.5.1
decorator               5.1.1
defusedxml              0.7.1
einops                  0.4.1
entmax                  1.0
entrypoints             0.3
filelock                3.6.0
fonttools               4.28.5
google-auth             2.3.3
google-auth-oauthlib    0.4.6
grpcio                  1.43.0
idna                    3.3
imageio                 2.16.2
imagesize               1.3.0
importlib-metadata      4.10.0
ipykernel               6.6.1
ipython                 7.31.0
ipython-genutils        0.2.0
jedi                    0.18.1
Jinja2                  3.0.3
joblib                  1.1.0
json5                   0.9.6
jsonschema              4.3.3
jupyter-client          7.1.0
jupyter-core            4.9.1
jupyter-server          1.13.1
jupyterlab              3.3.3
jupyterlab-pygments     0.1.2
jupyterlab-server       2.10.3
kiwisolver              1.3.2
Markdown                3.3.6
MarkupSafe              2.0.1
matplotlib              3.5.1
matplotlib-inline       0.1.3
mistune                 0.8.4
munch                   2.5.0
nbclassic               0.3.4
nbclient                0.5.9
nbconvert               6.4.0
nbformat                5.1.3
nest-asyncio            1.5.4
networkx                2.8
notebook                6.4.6
numpy                   1.22.0
oauthlib                3.1.1
opencv-python           4.5.5.62
opencv-python-headless  4.5.5.64
packaging               21.3
pandas                  1.3.5
pandocfilters           1.5.0
parso                   0.8.3
pickleshare             0.7.5
Pillow                  9.1.0
pip                     21.2.3
pix2tex                 0.0.12
prometheus-client       0.12.0
prompt-toolkit          3.0.24
protobuf                3.19.1
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pycocotools             2.0.4
pycparser               2.21
Pygments                2.11.2
pynput                  1.7.6
pyparsing               3.0.6
PyQt5                   5.15.6
PyQt5-Qt5               5.15.2
PyQt5-sip               12.10.1
PyQtWebEngine           5.15.5
PyQtWebEngine-Qt5       5.15.2
pyrsistent              0.18.0
python-dateutil         2.8.2
python-Levenshtein      0.12.2
pytz                    2021.3
PyWavelets              1.3.0
pywin32                 303
pywinpty                1.1.6
PyYAML                  6.0
pyzmq                   22.3.0
qudida                  0.0.4
regex                   2022.3.15
requests                2.27.1
requests-oauthlib       1.3.0
rsa                     4.8
sacremoses              0.0.49
scikit-image            0.19.2
scikit-learn            1.0.2
scipy                   1.7.3
screeninfo              0.8
Send2Trash              1.8.0
setuptools              57.4.0
six                     1.16.0
sniffio                 1.2.0
tensorboard             2.8.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
terminado               0.12.1
testpath                0.5.0
threadpoolctl           3.1.0
tifffile                2022.4.8
timm                    0.5.4
tokenizers              0.9.4
torch                   1.11.0
torchaudio              0.11.0
torchtext               0.12.0
torchvision             0.12.0
tornado                 6.1
tqdm                    4.62.3
traitlets               5.1.1
transformers            4.2.2
typing_extensions       4.1.1
urllib3                 1.26.8
wcwidth                 0.2.5
webencodings            0.5.1
websocket-client        1.2.3
Werkzeug                2.0.2
wheel                   0.37.1
x-transformers          0.15.0
zipp                    3.7.0
WARNING: You are using pip version 21.2.3; however, version 22.0.4 is available.
You should consider upgrading via the 'F:\Venv\pytorch_1.11\Scripts\python.exe -m pip install --upgrade pip' command.
```

**Comment by lukas-blecher** [comment]
The virtual environment seems fine. I can run it this way. Can you try the following:
- Does the same error occur when you run the cmd as administrator?
- make sure you are in the venv and try to execute `python -m pix2tex.gui`

**Comment by hagayhillel** [comment]
I have the same issue, tried to run cmd as admin and change the "model" folder permission, but still, it doesn't work.

**Comment by lukas-blecher** [comment]
A workaround would be to 
1. clone the repository
2. Then open a cmd and go to `LaTeX-OCR` and execute `pip install -e .[gui] -U`

But I don't know why you have this problem. I can't reproduce it with the information I have.
Can you execute the following python snippet? 
```python
import os
os.chdir('F:\\Venv\\pytorch_1.11\\lib\\site-packages\\pix2tex\\model')
```

**Comment by hagayhillel** [comment]
I've tried to follow your steps, but still no luck.

And executed the snippet, had no errors.

btw my `pix2tex` is not in virtual env.

**Comment by TITC** [comment]
> File "F:\Python\lib\importlib\resources.py", line 175, in _path_from_reader

I havn't seen any method name with `_path_from_reader` at python3.7 [importlib.resources.py](https://github.com/python/cpython/blob/3.7/Lib/importlib/resources.py)

but I do found these things at [python3.9.8 line 170~175](https://github.com/python/cpython/blob/bb3fdcfe95b9aeed13b7201ffbc634752ad8ecc9/Lib/importlib/resources.py#L170-L177)
![image](https://user-images.githubusercontent.com/35098797/163825553-036d9ffb-5e3b-49f7-94ac-f0c03732272b.png)

could you try to down grade python version to 3.7.13? @hagayhillel @calmisential 

if use conda env
```python
conda create --name latex_ocr python=3.7.13
```

**Comment by TITC** [comment]
Problem reproduced at python 3.9 env @hagayhillel @calmisential
```cmd

(test) C:\Users\Yuhang>latexocr
Traceback (most recent call last):
  File "S:\Users\Yuhang\anaconda3\envs\test\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "S:\Users\Yuhang\anaconda3\envs\test\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "S:\Users\Yuhang\anaconda3\envs\test\Scripts\latexocr.exe\__main__.py", line 7, in <module>
  File "S:\Users\Yuhang\anaconda3\envs\test\lib\site-packages\pix2tex\gui.py", line 316, in main
    with in_model_path():
  File "S:\Users\Yuhang\anaconda3\envs\test\lib\contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "S:\Users\Yuhang\anaconda3\envs\test\lib\site-packages\pix2tex\utils\utils.py", line 161, in in_model_path
    with path('pix2tex', 'model') as model_path:
  File "S:\Users\Yuhang\anaconda3\envs\test\lib\contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "S:\Users\Yuhang\anaconda3\envs\test\lib\importlib\resources.py", line 175, in _path_from_reader
    opener_reader = reader.open_resource(norm_resource)
  File "<frozen importlib._bootstrap_external>", line 1055, in open_resource
PermissionError: [Errno 13] Permission denied: 'S:\\Users\\Yuhang\\anaconda3\\envs\\test\\lib\\site-packages\\pix2tex\\model'
```

**Comment by lukas-blecher** [comment]
Thank you! I will work on a fix asap

**Comment by hagayhillel** [comment]
@TITC @lukas-blecher  It works! I downgraded my conda python version to 3.7.13 as @TITC  said
then reinstalled `pix2tex`, and everything works as expected.

I guess its python version issue, anyway thank you guys I really appreciate it

**Comment by lukas-blecher** [comment]
Solved in the newest version
`pip install -U pix2tex`
