### ISSUE TITLE
Can't install normally pyqt5

### ISSUE THREAD

**Issue by islambek243** [lukas-blecher/LaTeX-OCR#152]
`pip install pix2tex[gui]`
gives me
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
 spyder 5.1.5 requires pyqt5<5.13, but you have pyqt5 5.15.6 which is incompatible.
 spyder 5.1.5 requires pyqtwebengine<5.13, but you have pyqtwebengine 5.15.5 which is incompatible.
 Successfully installed PyQt5-5.15.6 PyQt5-sip-12.10.1
```
if i ignore it and enter
`latexocr --gnome`
it gives me
```
Traceback (most recent call last):
File "/home/islambek243/anaconda3/bin/latexocr", line 5, in <module>
from pix2tex.gui import main
File "/home/islambek243/anaconda3/lib/python3.9/site-packages/pix2tex/gui.py", line 7, in <module>
from PyQt5.QtWebEngineWidgets import QWebEngineView
ImportError: /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2: undefined symbol: krb5_ser_context_init, version krb5_3_MIT
```
If i don't ignore previous error and enter
`pip install pyqt5==5.12.3`
it gives me
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 5.1.5 requires pyqtwebengine<5.13, but you have pyqtwebengine 5.15.5 which is incompatible.
pyqtwebengine 5.15.5 requires PyQt5>=5.15.4, but you have pyqt5 5.12.3 which is incompatible.
Successfully installed pyqt5-5.12.3
```
it's endless circle...

**Comment by TITC** [comment]
No response in 48 hours. feel free to reopen it if you need further help. ^_^ @islambek243
