### ISSUE TITLE
run error in colab

### ISSUE THREAD

**Issue by lixumin-zai** [lukas-blecher/LaTeX-OCR#160]
```
!python -m pix2tex.train --config colab.yaml
-----------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/munch/__init__.py", line 103, in __getattr__
    return object.__getattribute__(self, k)
AttributeError: 'Munch' object has no attribute 'encoder_structure'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/munch/__init__.py", line 106, in __getattr__
    return self[k]
KeyError: 'encoder_structure'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/pix2tex/train.py", line 116, in <module>
    train(args)
  File "/usr/local/lib/python3.7/dist-packages/pix2tex/train.py", line 42, in train
    model = get_model(args)
  File "/usr/local/lib/python3.7/dist-packages/pix2tex/models/utils.py", line 41, in get_model
    if args.encoder_structure.lower() == 'vit':
  File "/usr/local/lib/python3.7/dist-packages/munch/__init__.py", line 108, in __getattr__
    raise AttributeError(k)
AttributeError: encoder_structure
```

**Comment by TITC** [comment]
you can use below config  for a quick fix.
```shell
!echo {backbone_layers: [2, 3, 7], betas: [0.9, 0.999], batchsize: 10, bos_token: 1, channels: 1, data: dataset/data/train.pkl, debug: true, decoder_args: {'attn_on_attn': true, 'cross_attend': true, 'ff_glu': true, 'rel_pos_bias': false, 'use_scalenorm': false}, dim: 256, encoder_depth: 4, eos_token: 2, epochs: 50, gamma: 0.9995, heads: 8, id: null, load_chkpt: 'weights.pth', lr: 0.001, lr_step: 30, max_height: 192, max_seq_len: 512, max_width: 672, min_height: 32, min_width: 32, model_path: checkpoints, name: mixed, num_layers: 4, num_tokens: 8000, optimizer: Adam, output_path: outputs, pad: false, pad_token: 0, patch_size: 16, sample_freq: 2000, save_freq: 1, scheduler: StepLR, seed: 42, temperature: 0.2, test_samples: 5, testbatchsize: 20, tokenizer: dataset/tokenizer.json, valbatches: 100, valdata: dataset/data/val.pkl, encoder_structure: hybrid} > colab.yaml
```

![image](https://user-images.githubusercontent.com/35098797/172135031-bf1d0b3c-2236-47fe-a1b9-fd7d701893ab.png)

---

main branch code will update after tested.
