### ISSUE TITLE
google/protobuf/pyext/descriptor.cc:358: bad argument to internal function

### ISSUE THREAD

**Issue by geek3000** [lukas-blecher/LaTeX-OCR#18]
Hello, i got this error went i run python pix2tex.

I have torch 1.7 with cuda.

**Comment by lukas-blecher** [comment]
This most likely is an error with the torch installation.
Could you confirm that the installation works properly?
Are you using Python 3.9? Maybe try using torch 1.8 
The code is compatible.

**Comment by geek3000** [comment]
Yes the installation worked properly. I have upgrade to torch 1.8 same problem. but i am using python 3.9

**Comment by lukas-blecher** [comment]
At which point is it failing?
Can you paste the stack trace please.

**Comment by geek3000** [comment]
`Predict LaTeX code for image ("?"/"h" for help). /home/newgenius/Téléchargements/discriminant.png
Traceback (most recent call last):
  File "pix2tex.py", line 189, in <module>
    pred = call_model(args, *objs, img=img)
  File "pix2tex.py", line 98, in call_model
    pred = post_process(token2str(dec, tokenizer)[0])
  File "/home/newgenius/dev/LaTeX-OCR/utils/utils.py", line 69, in token2str
    dec = [tokenizer.decode(tok) for tok in tokens]
  File "/home/newgenius/dev/LaTeX-OCR/utils/utils.py", line 69, in <listcomp>
    dec = [tokenizer.decode(tok) for tok in tokens]
  File "/home/newgenius/dev/anaconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 3083, in decode
    token_ids = to_py_obj(token_ids)
  File "/home/newgenius/dev/anaconda3/lib/python3.8/site-packages/transformers/file_utils.py", line 1662, in to_py_obj
    elif is_tf_available() and _is_tensorflow(obj):
  File "/home/newgenius/dev/anaconda3/lib/python3.8/site-packages/transformers/file_utils.py", line 1643, in _is_tensorflow
    import tensorflow as tf
  File "/home/newgenius/dev/anaconda3/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/newgenius/dev/anaconda3/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 41, in <module>
    from tensorflow.python.eager import context
  File "/home/newgenius/dev/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 32, in <module>
    from tensorflow.core.framework import function_pb2
  File "/home/newgenius/dev/anaconda3/lib/python3.8/site-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/home/newgenius/dev/anaconda3/lib/python3.8/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/home/newgenius/dev/anaconda3/lib/python3.8/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/home/newgenius/dev/anaconda3/lib/python3.8/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 141, in <module>
    ResourceHandleProto = _reflection.GeneratedProtocolMessageType('ResourceHandleProto', (_message.Message,), {
SystemError: google/protobuf/pyext/descriptor.cc:358: bad argument to internal function
`

**Comment by lukas-blecher** [comment]
Ok, so it is an issue with the huggingface transformers/tokenizers package. It supports torch and tensorflow and from the looks of it, it tries to call tensorflow.
Is your tensorflow installation valid? If not try uninstalling or reinstalling.
I'm not sure how to force the tokenizer to use pytorch in the backend which would solve the issue, I believe.

**Comment by geek3000** [comment]
The reinstallation on pytorch and tensorflow solve the problem thanks.
