### ISSUE TITLE
Error on running latexocr

### ISSUE THREAD

**Issue by DilicalFlame** [lukas-blecher/LaTeX-OCR#239]
On running the command `latexocr` I get the following error:

```
Traceback (most recent call last):
  File "/home/dilicalflame/.local/bin/latexocr", line 8, in <module>
    sys.exit(main())
  File "/home/dilicalflame/.local/lib/python3.10/site-packages/pix2tex/__main__.py", line 25, in main
    from .gui import main
  File "/home/dilicalflame/.local/lib/python3.10/site-packages/pix2tex/gui.py", line 7, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView
ImportError: libQt5WebChannel.so.5: cannot open shared object file: No such file or directory
```

**Comment by lukas-blecher** [comment]
That's some kind of pyqt5 dependency error.
Maybe you can try the PyQt6 #236 branch.
