### ISSUE TITLE
The LatexOcr() model is not properly working

### ISSUE THREAD

**Issue by Boluex** [lukas-blecher/LaTeX-OCR#263]
The code
model=LatexOCR()
# open_image=Image.open("/home/deji/Downloads/integration.png")
open_image=open("/home/deji/Downloads/integration.png", "rb")
image = Image.open(open_image)
print_output=model(image)
expr = sympify(print_output)
print(expr)

the error
Projects/pythonProject/msg.py
[W NNPACK.cpp:64] Could not initialize NNPACK! Reason: Unsupported hardware.
QSocketNotifier: Can only be used with threads started with QThread
Traceback (most recent call last):
  File "/home/deji/.local/lib/python3.10/site-packages/sympy/core/sympify.py", line 496, in sympify
    expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
  File "/home/deji/.local/lib/python3.10/site-packages/sympy/parsing/sympy_parser.py", line 1086, in parse_expr
    code = stringify_expr(s, local_dict, global_dict, _transformations)
  File "/home/deji/.local/lib/python3.10/site-packages/sympy/parsing/sympy_parser.py", line 892, in stringify_expr
    for toknum, tokval, _, _, _ in generate_tokens(input_code.readline):
  File "/usr/lib/python3.10/tokenize.py", line 523, in _tokenize
    raise TokenError("EOF in multi-line statement", (lnum, 0))
tokenize.TokenError: ('EOF in multi-line statement', (2, 0))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/deji/Desktop/deji/PycharmProjects/pythonProject/msg.py", line 188, in <module>
    expr = sympify(print_output)
  File "/home/deji/.local/lib/python3.10/site-packages/sympy/core/sympify.py", line 498, in sympify
    raise SympifyError('could not parse %r' % a, exc)
sympy.core.sympify.SympifyError: Sympify of expression 'could not parse '\\begin{array}{r l}{{\\mathrm{SolWe~}}{\\frac{2}{1}}{\\mathrm{~2}}x d x}\\\\ {{\\mathrm{~5~}}}&{{\\mathrm{~2}}}\\\\ {{\\mathrm{~5olution}{\\mathrm{:}}}}&{{\\mathrm{~5~}}x d x=\\left[x^{2}\\right]{\\begin{array}{l}{{\\mathrm{~2}}}\\\\ {\\mathrm{~2}}\\\\ {\\mathrm{~2}}&{{}=2^{2}-1^{2}=3}\\end{array}'' failed, because of exception being raised:
TokenError: ('EOF in multi-line statement', (2, 0))

please how can i fix it....
Kindly help me

**Comment by lukas-blecher** [comment]
The problem was not with LatexOCR but with `expr = sympify(print_output)`.
The error occured because the model didn't return valid latex code. So you'll have to catch this error and warn that the recognition failed
