### ISSUE TITLE
RuntimeError: The size of tensor a (88) must match the size of tensor b (57) at non-singleton dimension 1

### ISSUE THREAD

**Issue by bieshuohua503** [lukas-blecher/LaTeX-OCR#315]
when i use other dataset(https://www.kaggle.com/datasets/gregoryeritsyan/im2latex-230k) to train the model.
it shows error:
Traceback (most recent call last):
  File "C:/Natimi/LaTeX-OCR-main/pix2tex/train.py", line 57, in train
    loss = model.data_parallel(im[j:j+microbatch].to(device), device_ids=args.gpu_devices, tgt_seq=tgt_seq, mask=tgt_mask)*microbatch/args.batchsize
  File "C:\Natimi\LaTeX-OCR-main\pix2tex\models\utils.py", line 18, in data_parallel
    return self(x, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Natimi\LaTeX-OCR-main\pix2tex\models\utils.py", line 30, in forward
    encoded = self.encoder(x)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\timm\models\vision_transformer.py", line 363, in forward
    x = self.forward_features(x)
  File "C:\Natimi\LaTeX-OCR-main\pix2tex\models\hybrid.py", line 26, in forward_features
    x += self.pos_embed[:, pos_emb_ind]
RuntimeError: The size of tensor a (88) must match the size of tensor b (57) at non-singleton dimension 1

Process finished with exit code 1

why is this problem?

**Comment by domik017123** [comment]
I had a same problem in using other dataset. It might be a problem of input image size. Height and width of images have to be multiples of 32 pixel.

**Comment by bieshuohua503** [comment]
ok,thanks,
