### ISSUE TITLE
RuntimeError: The size of tensor a (137) must match the size of tensor b (100) at non-singleton dimension 1

### ISSUE THREAD

**Issue by bigbro13** [lukas-blecher/LaTeX-OCR#328]
When I train with my own data, the following problems occur.

Traceback (most recent call last):
  File "/home/wising/miniconda3/envs/latex_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/wising/miniconda3/envs/latex_env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/wising/miniconda3/envs/latex_env/lib/python3.8/site-packages/pix2tex/train.py", line 102, in <module>
    train(args)
  File "/home/wising/miniconda3/envs/latex_env/lib/python3.8/site-packages/pix2tex/train.py", line 57, in train
    loss = model.data_parallel(im[j:j+microbatch].to(device), device_ids=args.gpu_devices, tgt_seq=tgt_seq, mask=tgt_mask)*microbatch/args.batchsize
  File "/home/wising/miniconda3/envs/latex_env/lib/python3.8/site-packages/pix2tex/models/utils.py", line 18, in data_parallel
    return self(x, **kwargs)
  File "/home/wising/miniconda3/envs/latex_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wising/miniconda3/envs/latex_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wising/miniconda3/envs/latex_env/lib/python3.8/site-packages/pix2tex/models/utils.py", line 30, in forward
    encoded = self.encoder(x)
  File "/home/wising/miniconda3/envs/latex_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wising/miniconda3/envs/latex_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wising/miniconda3/envs/latex_env/lib/python3.8/site-packages/timm/models/vision_transformer.py", line 363, in forward
    x = self.forward_features(x)
  File "/home/wising/miniconda3/envs/latex_env/lib/python3.8/site-packages/pix2tex/models/hybrid.py", line 25, in forward_features
    x += self.pos_embed[:, pos_emb_ind]
RuntimeError: The size of tensor a (137) must match the size of tensor b (100) at non-singleton dimension 1

**Comment by bigbro13** [comment]
> @bigbro13 Running into this error myself, can you point me the right way if you resolved this error

Changing the pad in the configuration file to true may be slower, but it can handle image size issues
