### ISSUE TITLE
latexocr: DLL load failed while importing QtCore

### ISSUE THREAD

**Issue by MartinNiederl** [lukas-blecher/LaTeX-OCR#330]
I created a new conda env using:

```
conda create --name latex_ocr python=3.10
conda activate latex_ocr
conda install pytorch pytorch-cuda=11.8 -c pytorch -c nvidia
pip install "pix2tex[gui]"
```

Getting error:

```
(latex_ocr) > C:\Users\marti>latexocr
Traceback (most recent call last):
  File "D:\ProgramData\condaenvs\latex_ocr\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\ProgramData\condaenvs\latex_ocr\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\condaenvs\latex_ocr\Scripts\latexocr.exe\__main__.py", line 7, in <module>
  File "D:\ProgramData\condaenvs\latex_ocr\lib\site-packages\pix2tex\__main__.py", line 25, in main
    from .gui import main
  File "D:\ProgramData\condaenvs\latex_ocr\lib\site-packages\pix2tex\gui.py", line 21, in <module>
    import pix2tex.resources.resources
  File "D:\ProgramData\condaenvs\latex_ocr\lib\site-packages\pix2tex\resources\resources.py", line 6, in <module>
    from PySide6 import QtCore
ImportError: DLL load failed while importing QtCore: The specified procedure could not be found.
```

Also tried installing versions 6.5.1 and 6.5.2 of PyQt based on this https://github.com/lukas-blecher/LaTeX-OCR/issues/257#issuecomment-1651686937 but the error message is still the same.

**Comment by Pedsurgeon1** [comment]
I have the same issue, I tried 6.5.1, 6.5.2 and 6.5.3 but all gave the same error

**Comment by abenezerGithub** [comment]
thank you dude it also works for me thankyou

**Comment by duolanda** [comment]
> HI @MartinNiederl I had the same problem and I solved it as follows
> 
> I removed all packages that have different versions and installed only versions 6.5.1 for them all
> 
> you can do so by implementing these codes
> 
> pip uninstall -y PyQt6 PyQt6-Qt6 PyQt6-sip PyQt6-WebEngine PyQt6-WebEngine-Qt6
> 
> pip uninstall -y PySide6 PySide6-Addons PySide6-Essential shiboken6
> 
> pip install PyQt6==6.5.1 PyQt6-Qt6==6.5.1 PyQt6-WebEngine-Qt6==6.5.1 PyQt6-WebEngine
> 
> pip install PySide6-Essentials==6.5.1 PySide6==6.5.1 PySide6-Addons==6.5.1 shiboken6==6.5.1
> 
> after that install the latest version as recommended by the author
> 
> pip install "git+[https://github.com/lukas-blecher/LaTeX-OCR.git#egg=pix2tex[gui]](https://github.com/lukas-blecher/LaTeX-OCR.git#egg=pix2tex%5Bgui%5D)"
> 
> It works for me now

It works! Thank you very much!

**Comment by T1t2nium** [comment]
think you，it works well

**Comment by bernardo28** [comment]
> HI @MartinNiederl I had the same problem and I solved it as follows
> 
> I removed all packages that have different versions and installed only versions 6.5.1 for them all
> 
> you can do so by implementing these codes
> 
> pip uninstall -y PyQt6 PyQt6-Qt6 PyQt6-sip PyQt6-WebEngine PyQt6-WebEngine-Qt6
> 
> pip uninstall -y PySide6 PySide6-Addons PySide6-Essential shiboken6
> 
> pip install PyQt6==6.5.1 PyQt6-Qt6==6.5.1 PyQt6-WebEngine-Qt6==6.5.1 PyQt6-WebEngine
> 
> pip install PySide6-Essentials==6.5.1 PySide6==6.5.1 PySide6-Addons==6.5.1 shiboken6==6.5.1
> 
> after that install the latest version as recommended by the author
> 
> pip install "git+[https://github.com/lukas-blecher/LaTeX-OCR.git#egg=pix2tex[gui]](https://github.com/lukas-blecher/LaTeX-OCR.git#egg=pix2tex%5Bgui%5D)"
> 
> It works for me now

thank you so much still work  October 2024 :D

**Comment by creeras** [comment]
thanks. 
------
c:\pip>pip install PySide6-Essentials==6.5.1 PySide6==6.5.1 PySide6-Addons==6.5.1 shiboken6==6.5.1
ERROR: Ignored the following versions that require a different python version: 6.3.0 Requires-Python <3.11,>=3.6; 6.3.1 Requires-Python <3.11,>=3.6; 6.3.2 Requires-Python <3.11,>=3.6
ERROR: Could not find a version that satisfies the requirement PySide6-Essentials==6.5.1 (from versions: 6.4.0.1, 6.4.1, 6.4.2, 6.4.3, 6.5.0, 6.5.1.1, 6.5.2, 6.5.3, 6.6.0, 6.6.1, 6.6.2, 6.6.3, 6.6.3.1, 6.7.0, 6.7.1, 6.7.2, 6.7.3, 6.8.0, 6.8.0.1, 6.8.0.2)
ERROR: No matching distribution found for PySide6-Essentials==6.5.1

c:\pip>
c:\pip>pip install PySide6-Essentials==6.5.1.1 PySide6==6.5.1.1 PySide6-Addons==6.5.1.1 shiboken6==6.5.1.1

Collecting PySide6-Essentials==6.5.1.1
  Downloading PySide6_Essentials-6.5.1.1-cp37-abi3-win_amd64.whl.metadata (3.5 kB)
Collecting PySide6==6.5.1.1
  Downloading PySide6-6.5.1.1-cp37-abi3-win_amd64.whl.metadata (5.2 kB)
Collecting PySide6-Addons==6.5.1.1
  Downloading PySide6_Addons-6.5.1.1-cp37-abi3-win_amd64.whl.metadata (3.8 kB)
Collecting shiboken6==6.5.1.1
  Downloading shiboken6-6.5.1.1-cp37-abi3-win_amd64.whl.metadata (2.3 kB)
Downloading PySide6_Essentials-6.5.1.1-cp37-abi3-win_amd64.whl (72.8 MB)
   ---------------------------------------- 72.8/72.8 MB 10.8 MB/s eta 0:00:00
Downloading PySide6-6.5.1.1-cp37-abi3-win_amd64.whl (7.2 kB)
Downloading PySide6_Addons-6.5.1.1-cp37-abi3-win_amd64.whl (111.8 MB)
   ---------------------------------------- 111.8/111.8 MB 10.5 MB/s eta 0:00:00
Downloading shiboken6-6.5.1.1-cp37-abi3-win_amd64.whl (1.1 MB)
   ---------------------------------------- 1.1/1.1 MB 4.3 MB/s eta 0:00:00
Installing collected packages: shiboken6, PySide6-Essentials, PySide6-Addons, PySide6
  Attempting uninstall: PySide6-Essentials
    Found existing installation: PySide6_Essentials 6.8.0.2
    Uninstalling PySide6_Essentials-6.8.0.2:
      Successfully uninstalled PySide6_Essentials-6.8.0.2
Successfully installed PySide6-6.5.1.1 PySide6-Addons-6.5.1.1 PySide6-Essentials-6.5.1.1 shiboken6-6.5.1.1

**Comment by Norlandz** [comment]
Still have the problem, after downgrade the pyqt version.
