### ISSUE TITLE
Cant run with conda

### ISSUE THREAD

**Issue by Drakler** [lukas-blecher/LaTeX-OCR#341]
1 error its like ((( C:\LaTeX-OCR-0>latexocr
Traceback (most recent call last):
  File "\\?\C:\Users\Enis\miniconda3\Scripts\latexocr-script.py", line 33, in <module>
    sys.exit(load_entry_point('pix2tex==0.0.31', 'console_scripts', 'latexocr')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Enis\miniconda3\Lib\site-packages\pix2tex\__main__.py", line 25, in main
    from .gui import main
  File "C:\Users\Enis\miniconda3\Lib\site-packages\pix2tex\gui.py", line 7, in <module>
    from PyQt6 import QtCore, QtGui
ImportError: DLL load failed while importing QtCore: The specified procedure could not be found. )))

andd

error: `cargo rustc --lib --message-format=json-render-diagnostics --manifest-path Cargo.toml --release -v --features pyo3/extension-module --crate-type cdylib --` failed with code 101
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tokenizers
Failed to build tokenizers
ERROR: Could not build wheels for tokenizers, which is required to install pyproject.toml-based projects

**Comment by 54lH** [comment]
Similar issue when running in conda.
(base) C:\Users\xxxx>latexocr
Traceback (most recent call last):
  File "C:\Users\hliangap\AppData\Local\miniconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\hliangap\AppData\Local\miniconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\hliangap\AppData\Local\miniconda3\Scripts\latexocr.exe\__main__.py", line 7, in <module>
  File "C:\Users\hliangap\AppData\Local\miniconda3\lib\site-packages\pix2tex\__main__.py", line 25, in main
    from .gui import main
  File "C:\Users\hliangap\AppData\Local\miniconda3\lib\site-packages\pix2tex\gui.py", line 7, in <module>
    from PyQt6 import QtCore, QtGui
ImportError: DLL load failed while importing QtCore: The specified procedure could not be found.

**Comment by SWHL** [comment]
@54lH From the message, it appears that pyqt was not successfully installed.

**Comment by STEVENTAN100** [comment]
`pip list` and you can find imcopatible of pyqt6 and pyqt6-qt6, I think it's the problem of qt.
