### ISSUE TITLE
 numpy.dtype size changed, may indicate binary incompatibility.

### ISSUE THREAD

**Issue by payrim** [lukas-blecher/LaTeX-OCR#390]
```
Traceback (most recent call last):
  File "/directory/files/Programs/LaTeX-OCR/pix2tex/cli.py", line 1, in <module>
    from pix2tex.dataset.transforms import test_transform
  File "/usr/lib/python3.12/site-packages/pix2tex/dataset/transforms.py", line 1, in <module>
    import albumentations as alb
  File "/usr/lib/python3.12/site-packages/albumentations/__init__.py", line 6, in <module>
    from .augmentations import *
  File "/usr/lib/python3.12/site-packages/albumentations/augmentations/__init__.py", line 1, in <module>
    from .blur.functional import *
  File "/usr/lib/python3.12/site-packages/albumentations/augmentations/blur/__init__.py", line 1, in <module>
    from .functional import *
  File "/usr/lib/python3.12/site-packages/albumentations/augmentations/blur/functional.py", line 11, in <module>
    from albumentations.augmentations.functional import convolve
  File "/usr/lib/python3.12/site-packages/albumentations/augmentations/functional.py", line 9, in <module>
    import skimage
  File "/usr/lib/python3.12/site-packages/skimage/__init__.py", line 124, in <module>
    from ._shared import geometry
  File "geometry.pyx", line 1, in init skimage._shared.geometry
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**Comment by jschaefer-hub** [comment]
I experience the same issue. 

System: MacOS Sonoma 14.6.1
