### ISSUE TITLE
Can not open GUI with latexcor

### ISSUE THREAD

**Issue by VIRTUALWORLDHEAD0CAICAI** [lukas-blecher/LaTeX-OCR#405]
(p9) PS D:\LaTeX-OCR> latexocr

Traceback (most recent call last):
  File "C:\Users\50332\anaconda3\envs\p9\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\50332\anaconda3\envs\p9\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\50332\anaconda3\envs\p9\Scripts\latexocr.exe\__main__.py", line 7, in <module>
  File "C:\Users\50332\anaconda3\envs\p9\lib\site-packages\pix2tex\__main__.py", line 25, in main
    from .gui import main
  File "C:\Users\50332\anaconda3\envs\p9\lib\site-packages\pix2tex\gui.py", line 21, in <module>
    import pix2tex.resources.resources
  File "C:\Users\50332\anaconda3\envs\p9\lib\site-packages\pix2tex\resources\resources.py", line 6, in <module>
    from PySide6 import QtCore
ImportError: DLL load failed while importing QtCore: 找不到指定的程序。

**Comment by CuiOrange** [comment]
exactly same problem！do you fix that?

**Comment by CuiOrange** [comment]
> exactly same problem！do you fix that?

by the way,my  `pyqt6==6.6.1`

**Comment by VIRTUALWORLDHEAD0CAICAI** [comment]
> > exactly same problem！do you fix that?
> 
> by the way,my `pyqt6==6.6.1`

my pyqt6 = = 6.7.1

**Comment by xAlpharax** [comment]
same problem here

Traceback (most recent call last):
  File "/home/alphara/.pyenv/versions/menu_gather/bin/latexocr", line 8, in <module>
    sys.exit(main())
  File "/home/alphara/.pyenv/versions/3.10.14/envs/menu_gather/lib/python3.10/site-packages/pix2tex/__main__.py", line 25, in main
    from .gui import main
  File "/home/alphara/.pyenv/versions/3.10.14/envs/menu_gather/lib/python3.10/site-packages/pix2tex/gui.py", line 21, in <module>
    import pix2tex.resources.resources
  File "/home/alphara/.pyenv/versions/3.10.14/envs/menu_gather/lib/python3.10/site-packages/pix2tex/resources/resources.py", line 6, in <module>
    from PySide6 import QtCore
ImportError: /home/alphara/.pyenv/versions/3.10.14/envs/menu_gather/lib/python3.10/site-packages/PySide6/libpyside6.abi3.so.6.8: undefined symbol: _Z8qmemrchrPKvim, version Qt_6

Neither pix2tex_gui or latexocr working

**Comment by FreshGerry** [comment]
From the issues “Conflinct between libraries PyQt6 and PySide6, when lunching the GUI #389”， they have give the solution.
在 envs\pytorch\Lib\site-packages\pix2tex\resources的路径，将resources\resources.py ，把“from PySide6 import QtCore”修复为“from PyQt6 import QtCore”

**Comment by 1435902835** [comment]
> From the issues “Conflinct between libraries PyQt6 and PySide6, when lunching the GUI #389”， they have give the solution.从问题“当启动GUI #389 时，库PyQt6和PySide6之间的冲突"，他们给出了解决方案。 在 envs\pytorch\Lib\site-packages\pix2tex\resources的路径，将resources\resources.py ，把“from PySide6 import QtCore”修复为“from PyQt6 import QtCore”在 envs\pytorch\Lib\site-packages\pix2tex\resources的路径下，将resources\resources.py，把“from PySide6 import QtCore”修复为“from PyQt6 import QtCore”

thank you

**Comment by xAlpharax** [comment]
> After downgrading the version of PySide6 to the same version of PyQt6==6.7.3, I resolved the issue.

Thank you, this fixed it for me:
pip install PyQt6==6.7.1
pip install PySide6==6.7.1

generally this program needs PySide6 and PyQt6 versions to match in the environment.

**Comment by Biubush** [comment]
I managed to fix it by executing these commands：
```bash
pip uninstall pillow
pip install pillow
```
Although I'm not sure why this happened
