### ISSUE TITLE
Compatibility : Missing key(s)

### ISSUE THREAD

**Issue by realasking** [lukas-blecher/LaTeX-OCR#54]
Hi, author.
Thanks for your work. It will be great convenient for converting formulas to latex codes offline by this software.
I had installed its requirements under manjaro Linux today; however, it still threw an error like below if I executed the command `python gui.py`:
```python
Traceback (most recent call last):
  File ".../LaTeX-OCR/gui.py", line 274, in <module>
    ex = App(arguments)
  File ".../LaTeX-OCR/gui.py", line 26, in __init__
    self.initModel()
  File ".../LaTeX-OCR/gui.py", line 33, in initModel
    args, *objs = pix2tex.initialize(self.args)
  File ".../LaTeX-OCR/pix2tex.py", line 55, in initialize
    model.load_state_dict(torch.load(args.checkpoint, map_location=args.device))
  File "/usr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1406, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Model:
        Missing key(s) in state_dict: "decoder.net.attn_layers.layers.2.1.net.3.weight", "decoder.net.attn_layers.layers.2.1.net.3.bias", "decoder.net.attn_layers.layers.5.1.net.3.weight", "decoder.net.attn_layers.layers.5.1.net.3.bias", "decoder.net.attn_layers.layers.8.1.net.3.weight", "decoder.net.attn_layers.layers.8.1.net.3.bias", "decoder.net.attn_layers.layers.11.1.net.3.weight", "decoder.net.attn_layers.layers.11.1.net.3.bias". 
        Unexpected key(s) in state_dict: "decoder.net.attn_layers.layers.2.1.net.2.weight", "decoder.net.attn_layers.layers.2.1.net.2.bias", "decoder.net.attn_layers.layers.5.1.net.2.weight", "decoder.net.attn_layers.layers.5.1.net.2.bias", "decoder.net.attn_layers.layers.8.1.net.2.weight", "decoder.net.attn_layers.layers.8.1.net.2.bias", "decoder.net.attn_layers.layers.11.1.net.2.weight", "decoder.net.attn_layers.layers.11.1.net.2.bias". 
```
I would like to know what caused this problem and how can I run the code correctly?
Thanks.

**Comment by lukas-blecher** [comment]
I think this is most likely a dependency issue.
What version of x-transformers do you have installed? can you post the output of `pip list`?

**Comment by realasking** [comment]
> I think this is most likely a dependency issue. What version of x-transformers do you have installed? can you post the output of `pip list`?

Thanks for your reply, and I will post the package list below. Most installed packages were provided by the manjaro distribution, and only several of which cannot be found  in the repo were installed using the pip command. While the version number of installed `x-transformers` is `0.20.5`.

```bash
Package                       Version
----------------------------- ---------------------------------------------------------------------------------
absl-py                       0.13.0
abydos                        0.5.0
alabaster                     0.7.12
albumentations                1.1.0
anyio                         3.3.2
anytree                       2.8.0
apipkg                        1.5
apparmor                      3.0.3
appdirs                       1.4.4
application-utility           1.3.2
argh                          0.26.2
argon2-cffi                   21.1.0
arrow                         1.1.1
astor                         0.8.1
astroid                       2.8.2
astropy                       4.3.1
asttokens                     2.0.5
astunparse                    1.6.3
async-generator               1.10
atomicwrites                  1.4.0
attrs                         21.2.0
Automat                       20.2.0
autopep8                      1.5.7
av                            8.0.3
Babel                         2.9.1
backcall                      0.2.0
bcrypt                        3.2.0
Beaker                        1.11.0
beautifulsoup4                4.9.3
binaryornot                   0.4.4
black                         21.9b0
bleach                        4.1.0
Bottleneck                    1.3.2
Brlapi                        0.8.3
bs4                           0.0.1
btrfsutil                     5.14.2
CacheControl                  0.12.6
cachetools                    4.2.3
ceph                          1.0.0
ceph-volume                   1.0.0
cephfs                        2.0.0
cephfs-shell                  0.0.1
certifi                       2021.10.8
cffi                          1.14.6
chardet                       4.0.0
charset-normalizer            2.0.4
clang                         5.0
click                         8.0.3
cloudpickle                   1.6.0
colorama                      0.4.4
commonmark                    0.9.1
contextlib2                   0.6.0.post1
cookiecutter                  1.7.3
cryptography                  3.4.8
cupshelpers                   1.0
curio                         1.5
cycler                        0.10.0
Cython                        0.29.24
debugpy                       1.5.0
decorator                     5.1.0
defusedxml                    0.7.1
deprecation                   2.1.0
diff-match-patch              20200713
distlib                       0.3.3
distro                        1.6.0
dnspython                     2.1.0
Dockbarx                      1.0b0
docopt                        0.6.2
docutils                      0.17.1
EditorConfig                  0.12.3
einops                        0.3.2
entmax                        1.0
entrypoints                   0.3
essential-pathway             1.0.2
evdev                         1.4.0
filelock                      3.0.12
flake8                        3.9.2
flatbuffers                   2.0.0
future                        0.18.2
gast                          0.4.0
geographiclib                 1.52
geopy                         2.2.0
gmpy2                         2.1.0rc1
google-auth                   1.34.0
google-auth-oauthlib          0.4.4
google-pasta                  0.2.0
grpcio                        1.41.0
h5py                          3.3.0
helpdev                       0.7.1
html5lib                      1.1
huggingface-hub               0.1.2
idna                          3.2
imagecodecs                   2021.8.26
imageio                       2.10.3
imagesize                     1.2.0
imgaug                        0.4.0
importlib-metadata            4.8.1
imread                        0.7.3
inflection                    0.5.1
iniconfig                     1.1.1
intervaltree                  3.1.0
ipykernel                     6.4.1
ipython                       7.28.0
ipython-genutils              0.2.0
ipywidgets                    7.6.3
isc                           2.0
isort                         5.9.3
jedi                          0.18.0
jeepney                       0.7.1
jellyfish                     0.8.8
Jinja2                        3.0.2
jinja2-time                   0.2.0
joblib                        1.0.1
json5                         0.9.6
jsonschema                    3.2.0
jupyter-client                6.1.12
jupyter-console               6.4.0
jupyter-core                  4.8.1
jupyter-packaging             0.10.6
jupyterlab-pygments           0.1.2
keras                         2.6.0
Keras-Applications            1.0.8
Keras-Preprocessing           1.1.2
keyring                       23.0.1
keyutils                      0.6
kiwisolver                    1.3.2
latex2mathml                  3.61.0
latexcodec                    2.0.1
lazy-object-proxy             1.6.0
lensfun                       0.3.95
LibAppArmor                   3.0.3
libfdt                        1.6.1
libtorrent                    1.2.14-build-libtorrent-rasterbar-src-libtorrent-rasterbar-1.2.14-bindings-python
libvirt-python                7.8.0
lit                           12.0.1.dev0
louis                         3.19.0
lxml                          4.6.3
lz4                           2.2.1
Mako                          1.1.5
Markdown                      3.3.4
MarkupSafe                    2.0.1
matplotlib                    3.4.3
matplotlib-inline             0.1.2
mccabe                        0.6.1
meson                         0.59.2
mistune                       0.8.4
more-itertools                8.10.0
mpi4py                        3.0.3
mpmath                        1.2.1
msgpack                       1.0.2
multidict                     5.1.0
munch                         2.5.0
mypy-extensions               0.4.3
nbclient                      0.5.4
nbconvert                     6.1.0
nbformat                      5.1.3
nest-asyncio                  1.5.1
netsnmp-python                1.0a1
networkx                      2.6.3
nltk                          3.6.4
nose                          1.3.7
notebook                      6.4.4
npyscreen                     4.10.5
numexpr                       2.7.3
numpy                         1.21.2
numpydoc                      1.1.0
oauthlib                      3.1.1
OpenCC                        1.1.2
opencv-python-headless        4.5.4.58
ordered-set                   4.0.2
outcome                       1.1.0
packaging                     20.9
pacman-mirrors                4.21.5
pandas                        1.3.3
pandocfilters                 1.4.3
paramiko                      2.7.2
parso                         0.8.2
pathspec                      0.9.0
pathtools                     0.1.2
patsy                         0.5.1
pbr                           5.6.0
pep517                        0.11.0
petsc4py                      3.16.1
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        8.3.2
pip                           20.3.4
pip-search                    0.0.7
Pivy                          0.6.6
platformdirs                  2.4.0
pluggy                        0.13.1
ply                           3.11
polib                         1.1.1
poyo                          0.5.0
prettytable                   0.7.2
progress                      1.5
prometheus-client             0.11.0
prompt-toolkit                3.0.20
protobuf                      3.17.3
psutil                        5.8.0
ptyprocess                    0.7.0
pwquality                     1.4.4
py                            1.10.0
pyaml                         21.8.3
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pybind11                      2.8.0
pycairo                       1.20.1
pycocotools                   2.0.2
pycodestyle                   2.7.0
pycparser                     2.20
pycups                        2.0.1
pycurl                        7.44.1
pydocstyle                    6.1.1
pydot                         1.4.2
pyerfa                        2.0.0.1
pyflakes                      2.3.1
Pygments                      2.10.0
PyGObject                     3.40.1
pylint                        2.11.1
pyls-black                    0.4.6
pyls-spyder                   0.3.2
Pympler                       0.9
PyNaCl                        1.4.0
pynput                        1.7.4
pyopencl                      2021.1.4
pyOpenSSL                     20.0.1
pyparsing                     2.4.7
PyQt3D                        5.15.4
PyQt5                         5.15.4
PyQt5-sip                     12.9.0
PyQtChart                     5.15.4
PyQtDataVisualization         5.15.4
PyQtNetworkAuth               5.15.4
PyQtPurchasing                5.15.4
PyQtWebEngine                 5.15.4
pyrsistent                    0.18.0
PySide2                       5.15.2
pysmbc                        1.0.23
PySocks                       1.7.1
PyStemmer                     2.0.1
pytest                        6.2.5
python-dateutil               2.8.2
python-jsonrpc-server         0.4.0
python-language-server        0.36.2
python-Levenshtein            0.12.2
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.2.1
python-mpd2                   3.0.4
python-slugify                5.0.2
python-xlib                   0.31
pytools                       2021.2.8
pytz                          2021.1
PyWavelets                    1.1.1
pyxDamerauLevenshtein         1.7.0
pyxdg                         0.27
PyYAML                        5.4.1
pyzmq                         22.2.1
QDarkStyle                    3.0.2
QScintilla                    2.13.0
qstylizer                     0.2.0
QtAwesome                     1.0.2
qtconsole                     5.1.1
QtPy                          1.9.0
qudida                        0.0.4
rados                         2.0.0
rbd                           2.0.0
regex                         2021.8.28
reportlab                     3.6.1
requests                      2.26.0
requests-oauthlib             1.3.0
requests-unixsocket           0.2.0
resolvelib                    0.5.5
retrying                      1.3.3
rgw                           2.0.0
rich                          10.11.0
rope                          0.19.0
rsa                           4.7.2
Rtree                         0.9.7
sacremoses                    0.0.35
scikit-image                  0.18.3
scikit-learn                  1.0.1
scipy                         1.7.1
screeninfo                    0.7
SecretStorage                 3.3.1
Send2Trash                    1.8.0
setuptools                    57.4.0
Shapely                       1.7.1
shiboken2                     5.15.2
SimpleITK                     2.1.0
simplejson                    3.17.5
sip                           4.19.25
six                           1.16.0
sniffio                       1.2.0
snowballstemmer               2.1.0
sortedcontainers              2.4.0
soupsieve                     2.2.1
Sphinx                        4.2.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder-kernels                2.0.1
statsmodels                   0.12.2
sympy                         1.9
team                          1.0
termcolor                     1.1.0
terminado                     0.11.1
testpath                      0.5.0
text-unidecode                1.3
textdistance                  4.2.1
threadpoolctl                 3.0.0
three-merge                   0.1.1
tifffile                      2021.11.2
timm                          0.4.12
tinycss2                      1.1.0
tokenizers                    0.10.3
toml                          0.10.2
tomli                         1.2.1
tomlkit                       0.7.2
torch                         1.9.1
torchtext                     0.10.0a0+0d670e0
torchvision                   0.11.0a0
tornado                       6.1
tqdm                          4.62.3
traitlets                     5.1.0
transformers                  4.12.3
trio                          0.19.0
typing-extensions             3.10.0.2
udiskie                       2.3.3
ujson                         4.2.0
Unidecode                     1.3.2
urllib3                       1.26.6
virtualenv                    20.8.0
watchdog                      0.10.7
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              0.59.0
Werkzeug                      2.0.2
wheel                         0.37.0
widgetsnbextension            3.5.1
wrapt                         1.12.1
wurlitzer                     2.1.1
wxPython                      4.0.7.post2
x-transformers                0.20.5
yapf                          0.31.0
zipp                          3.6.0
zope.event                    4.5.0
zope.interface                5.4.0
```

**Comment by lukas-blecher** [comment]
ok I think that's the problem. In the requirements I listed x-transformers at another version because there were breaking changes. Please try
`pip install -U x-transformers==0.15.0`

**Comment by realasking** [comment]
> pip install -U x-transformers==0.15.0

Oh, it works. Thank you very much. ^_^
