### ISSUE TITLE
ModuleNotFoundError: No module named 'tokenizers.tokenizers' 

### ISSUE THREAD

**Issue by mrd33p** [lukas-blecher/LaTeX-OCR#77]
Why it stopped working?
I have tokenizers version 0.9.4

![image](https://user-images.githubusercontent.com/85106864/149164287-2c705804-f3e4-4bd4-9b80-b92fb6c8bf35.png)

```
(base) PS C:\Users\DELL\Downloads\LaTeX-OCR-main> python gui.py
Traceback (most recent call last):
  File "C:\Users\DELL\Downloads\LaTeX-OCR-main\gui.py", line 16, in <module>
    import pix2tex
  File "C:\Users\DELL\Downloads\LaTeX-OCR-main\pix2tex.py", line 1, in <module>
    from dataset.dataset import test_transform
  File "C:\Users\DELL\Downloads\LaTeX-OCR-main\dataset\__init__.py", line 6, in <module>
    import dataset.dataset
  File "C:\Users\DELL\Downloads\LaTeX-OCR-main\dataset\dataset.py", line 15, in <module>
    from transformers import PreTrainedTokenizerFast
  File "e:\ProgramData\Anaconda3\lib\site-packages\transformers\__init__.py", line 2098, in __getattr__
    return super().__getattr__(name)
  File "e:\ProgramData\Anaconda3\lib\site-packages\transformers\file_utils.py", line 1464, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "e:\ProgramData\Anaconda3\lib\site-packages\transformers\__init__.py", line 2092, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "e:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "e:\ProgramData\Anaconda3\lib\site-packages\transformers\tokenization_utils_fast.py", line 25, in <module>
    from tokenizers import Encoding as EncodingFast
  File "e:\ProgramData\Anaconda3\lib\site-packages\tokenizers\__init__.py", line 79, in <module>
    from .tokenizers import (
ModuleNotFoundError: No module named 'tokenizers.tokenizers'
```

**Comment by lukas-blecher** [comment]
I have no idea. The versions should be correct. Maybe try reinstalling 
```bash
pip install --force-reinstall tokenizers==0.9.4 transformers==4.2.2
```

**Comment by mrd33p** [comment]
It starts now but just closes automatically when I snip.

**Comment by lukas-blecher** [comment]
If that worked maybe try to reinstall all dependencies

**Comment by mrd33p** [comment]
Its works when I use pix2tex.py with the saved images; there is some problem with GUI.
